chore!: downgrade contracts to soroban-sdk v26 (#16)
This reverts #11 / f073ab697221bb74042bcad1d982711f71c5800f

Cannot currently deploy v27-built contracts to mainnet. We get:

```
error: the deployed smart contract registry.wasm was built with Soroban Rust SDK v27.0.0-rc.1#6656a27d81fe6832919c49f226b9fc76b7dae5c1, a release candidate version not intended for use with the Stellar Public Network.
```

Validators are scheduled to vote on activating Protocol 27 on July 8,
2026. We will need to update to SDK v27 at this time.